name: machine-learning-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10       # 3.10.13
  - make=4.3          # 4.3
  - matplotlib=3.8    # 3.8.1
  - numpy=1.26        # 1.26.0
  - pandas=2.1        # 2.1.3
  - scikit-learn=1.3  # 1.3.2
  - scipy=1.11        # 1.11.3
